spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 200
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      maximum-pool-size: 50
      max-lifetime: 30000
